version: "2"

services:
  db_postgres:
    image: 'postgres:13'
    container_name: db_postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_ROOT_PASSWORD=password
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=medicines
